version: '3.1'
services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - 3307:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./tattoo.sql:/docker-entrypoint-initdb.d/tattoo.sql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8089:80
      
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    environment:
      - TZ=Europe/London
    security_opt :
      - seccomp:unconfined
    ports:
      - 3001:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    links:
      - mariadb
      

  portanier_agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer_data:/data
    ports:
      - 9001:9000

  nginx:
    build: nginx
    restart: always
    ports:
      - 8081:80
   
volumes:
  mariadb:
  portainer_data:
